spring.application.name=app.brunosantos.pradvisor
server.port=8080
server.servlet.context-path=/

github.token=${GITHUB_TOKEN:github-token}

claude.desktop.url=${CLAUDE_DESKTOP_URL:http://localhost:3000}

logging.level.root=INFO
logging.level.com.example.prreview=DEBUG

spring.mvc.async.request-timeout=120000